code --install-extension aaron-bond.better-comments
code --install-extension asvetliakov.snapshot-tools
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension cmstead.jsrefactor
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.auto-rename-tag
code --install-extension HookyQR.beautify
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-python.python
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension nobuhito.printcode
code --install-extension Orta.vscode-jest
code --install-extension PKief.material-icon-theme
code --install-extension ritwickdey.LiveServer
code --install-extension wix.vscode-import-cost
code --install-extension zhuangtongfa.Material-theme